project:
  type: website

website:
  title: "Gustavo C. X. |  AI, Data Science & Analytics"
  favicon: "favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home
      # - href: cases.qmd
      - href: portfolio.qmd
        text: Data Portfolio
      - href: blog.qmd
        text: Blog
      # - href: research.qmd
      #   text: ML Research
      # - href: aiprompts.qmd
      #   text: AI Prompts
      # - href: testmonials.qmd
      #   text: Testmonials
      - about.qmd
      - href: schedule.qmd
        text: Book a Session
      # - href: https://calendly.com/gustavocx/30m
      #   text: Book a Session
      - href: mailto:gustavocx@outlook.com
        icon: envelope
      # - icon: github
      #   href: https://github.com/gustavocxavier
      # - icon: twitter
      #   href: https://twitter.com/gustavocxtech
format:
  html:
    theme:
      # dark: darkly
      dark: [darkly, styles_dark.scss]
      # dark: [cosmo, styles_dark.scss]
      light: flatly

execute:
  freeze: false
#  freeze: auto

# execute:
#   freeze: true  # never re-execute computational content during project render

editor: source

